/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package morelia.tecnm.tap_cinepolis;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import morelia.tecnm.tap_cinepolis.modelos.Funcion;
import morelia.tecnm.tap_cinepolis.modelos.ManejadorPHP;
import morelia.tecnm.tap_cinepolis.modelos.Pelicula;
import morelia.tecnm.tap_cinepolis.modelos.Usuario;



/**
 *
 * @author DELL
 */
public class MenuPeliculas extends javax.swing.JFrame {

    private Usuario usuario;
    private Funcion funcion;
    private Pelicula pelicula;
    private ArrayList<String> horarios;
    
    /**
     * Creates new form MenuPeliculas
     */
    public MenuPeliculas() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public MenuPeliculas(Usuario usuario) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.usuario = usuario;
        setLocationRelativeTo(null);
        setIcon();
        datosPelicula0();
        datosPelicula1();
        datosPelicula2();
        datosPelicula3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen0 = new javax.swing.JLabel();
        lblNombrePelicula0 = new javax.swing.JLabel();
        comboHorarios0 = new javax.swing.JComboBox<>();
        btnComprarAsientos0 = new javax.swing.JButton();
        btnSinopsis0 = new javax.swing.JButton();
        lblImagen1 = new javax.swing.JLabel();
        lblNombrePelicula1 = new javax.swing.JLabel();
        comboHorarios1 = new javax.swing.JComboBox<>();
        btnComprarAsientos1 = new javax.swing.JButton();
        btnSinopsis1 = new javax.swing.JButton();
        lblImagen2 = new javax.swing.JLabel();
        lblNombrePelicula2 = new javax.swing.JLabel();
        comboHorarios2 = new javax.swing.JComboBox<>();
        btnComprarAsientos2 = new javax.swing.JButton();
        btnSinopsis2 = new javax.swing.JButton();
        lblImagen3 = new javax.swing.JLabel();
        lblNombrePelicula3 = new javax.swing.JLabel();
        comboHorarios3 = new javax.swing.JComboBox<>();
        btnComprarAsientos3 = new javax.swing.JButton();
        btnSinopsis3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHistorialBoletos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagen0.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\ToyStoryPoster.jpg")); // NOI18N

        lblNombrePelicula0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombrePelicula0.setText("Nombre de la película");

        comboHorarios0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboHorarios0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnComprarAsientos0.setBackground(new java.awt.Color(20, 32, 106));
        btnComprarAsientos0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComprarAsientos0.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarAsientos0.setText("Comprar asientos");
        btnComprarAsientos0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAsientos0ActionPerformed(evt);
            }
        });

        btnSinopsis0.setBackground(new java.awt.Color(48, 113, 255));
        btnSinopsis0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSinopsis0.setForeground(new java.awt.Color(255, 255, 255));
        btnSinopsis0.setText("Ver sinopsis");

        lblImagen1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\SpiderManPoster.jpg")); // NOI18N

        lblNombrePelicula1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombrePelicula1.setText("Nombre de la película");

        comboHorarios1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboHorarios1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnComprarAsientos1.setBackground(new java.awt.Color(20, 32, 106));
        btnComprarAsientos1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComprarAsientos1.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarAsientos1.setText("Comprar asientos");
        btnComprarAsientos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAsientos1ActionPerformed(evt);
            }
        });

        btnSinopsis1.setBackground(new java.awt.Color(48, 113, 255));
        btnSinopsis1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSinopsis1.setForeground(new java.awt.Color(255, 255, 255));
        btnSinopsis1.setText("Ver sinopsis");

        lblImagen2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\StarWarsPoster.jpg")); // NOI18N
        lblImagen2.setText("Imagen2");

        lblNombrePelicula2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombrePelicula2.setText("Nombre de la película");

        comboHorarios2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboHorarios2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnComprarAsientos2.setBackground(new java.awt.Color(20, 32, 106));
        btnComprarAsientos2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComprarAsientos2.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarAsientos2.setText("Comprar asientos");
        btnComprarAsientos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAsientos2ActionPerformed(evt);
            }
        });

        btnSinopsis2.setBackground(new java.awt.Color(48, 113, 255));
        btnSinopsis2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSinopsis2.setForeground(new java.awt.Color(255, 255, 255));
        btnSinopsis2.setText("Ver sinopsis");

        lblImagen3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\ZeldaPoster.jpg")); // NOI18N
        lblImagen3.setText("Imagen3");

        lblNombrePelicula3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombrePelicula3.setText("Nombre de la película");

        comboHorarios3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboHorarios3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnComprarAsientos3.setBackground(new java.awt.Color(20, 32, 106));
        btnComprarAsientos3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComprarAsientos3.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarAsientos3.setText("Comprar asientos");
        btnComprarAsientos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAsientos3ActionPerformed(evt);
            }
        });

        btnSinopsis3.setBackground(new java.awt.Color(48, 113, 255));
        btnSinopsis3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSinopsis3.setForeground(new java.awt.Color(255, 255, 255));
        btnSinopsis3.setText("Ver sinopsis");

        jPanel1.setBackground(new java.awt.Color(20, 32, 106));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\logoCinepolis.jpg")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\iconoUsuario.PNG")); // NOI18N

        btnHistorialBoletos.setBackground(new java.awt.Color(20, 32, 106));
        btnHistorialBoletos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHistorialBoletos.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialBoletos.setText("Mis boletos");
        btnHistorialBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialBoletosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHistorialBoletos)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(316, 316, 316))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHistorialBoletos)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImagen0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagen1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombrePelicula0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboHorarios0, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombrePelicula1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboHorarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprarAsientos0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSinopsis0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSinopsis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComprarAsientos1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(258, 258, 258)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombrePelicula2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboHorarios2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombrePelicula3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboHorarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprarAsientos2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnSinopsis2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComprarAsientos3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnSinopsis3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNombrePelicula2)
                                .addComponent(btnComprarAsientos2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboHorarios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSinopsis2)))
                        .addComponent(lblImagen0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagen2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombrePelicula0)
                            .addComponent(btnComprarAsientos0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboHorarios0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSinopsis0))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombrePelicula3)
                            .addComponent(btnComprarAsientos3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboHorarios3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSinopsis3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombrePelicula1)
                            .addComponent(btnComprarAsientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboHorarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSinopsis1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblImagen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagen1)))
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarAsientos0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAsientos0ActionPerformed
        funcion = obtenerFuncion("2");
        new ComprarAsientos(usuario, funcion).setVisible(true);
    }//GEN-LAST:event_btnComprarAsientos0ActionPerformed

    private void btnHistorialBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialBoletosActionPerformed
        new HistorialBoletos(usuario).setVisible(true);
    }//GEN-LAST:event_btnHistorialBoletosActionPerformed

    private void btnComprarAsientos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAsientos1ActionPerformed
        funcion = obtenerFuncion("3");
        new ComprarAsientos(usuario, funcion).setVisible(true);
    }//GEN-LAST:event_btnComprarAsientos1ActionPerformed

    private void btnComprarAsientos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAsientos2ActionPerformed
        funcion = obtenerFuncion("4");
        new ComprarAsientos(usuario, funcion).setVisible(true);
    }//GEN-LAST:event_btnComprarAsientos2ActionPerformed

    private void btnComprarAsientos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAsientos3ActionPerformed
        funcion = obtenerFuncion("5");
        new ComprarAsientos(usuario, funcion).setVisible(true);
    }//GEN-LAST:event_btnComprarAsientos3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPeliculas().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarAsientos0;
    private javax.swing.JButton btnComprarAsientos1;
    private javax.swing.JButton btnComprarAsientos2;
    private javax.swing.JButton btnComprarAsientos3;
    private javax.swing.JButton btnHistorialBoletos;
    private javax.swing.JButton btnSinopsis0;
    private javax.swing.JButton btnSinopsis1;
    private javax.swing.JButton btnSinopsis2;
    private javax.swing.JButton btnSinopsis3;
    private javax.swing.JComboBox<String> comboHorarios0;
    private javax.swing.JComboBox<String> comboHorarios1;
    private javax.swing.JComboBox<String> comboHorarios2;
    private javax.swing.JComboBox<String> comboHorarios3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen0;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblNombrePelicula0;
    private javax.swing.JLabel lblNombrePelicula1;
    private javax.swing.JLabel lblNombrePelicula2;
    private javax.swing.JLabel lblNombrePelicula3;
    // End of variables declaration//GEN-END:variables

    private Funcion obtenerFuncion(String idFuncion) {
        try{
        ManejadorPHP m = new ManejadorPHP();
        return m.obtenerFuncionPorID(idFuncion);    
        }catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error en la conexión. Intente más tarde.");
        }
        return null;
    }
    
    private Pelicula obtenerPelicula(String idPelicula) {
        try{
        ManejadorPHP m = new ManejadorPHP();
        return m.obtenerPeliculaPorID(idPelicula);    
        }catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error en la conexión. Intente más tarde.");
        }
        return null;
    }
    
    private void obtenerHorarios(String idFuncion){
        try {
            ManejadorPHP m = new ManejadorPHP();
            
            horarios = m.enlistaHorarios(idFuncion);
        } 
        catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error en la conexión. Intente más tarde.");
        }
    }

    private void datosPelicula0() {
        funcion = obtenerFuncion("2");
        
        pelicula = obtenerPelicula("" + funcion.getIdPelicula());
        lblNombrePelicula0.setText("" + pelicula.getNombre());
        
        obtenerHorarios("" + funcion.getIdFuncion());
        comboHorarios0.removeAllItems();
        for(String e : horarios) {
            comboHorarios0.addItem(e);
        }
    }

    private void datosPelicula1() {
        funcion = obtenerFuncion("3");
        
        pelicula = obtenerPelicula("" + funcion.getIdPelicula());
        lblNombrePelicula1.setText("" + pelicula.getNombre());
        
        obtenerHorarios("" + funcion.getIdFuncion());
        comboHorarios1.removeAllItems();
        for(String e : horarios) {
            comboHorarios1.addItem(e);
        }
    }

    private void datosPelicula2() {
        funcion = obtenerFuncion("4");
        
        pelicula = obtenerPelicula("" + funcion.getIdPelicula());
        lblNombrePelicula2.setText("" + pelicula.getNombre());
        
        obtenerHorarios("" + funcion.getIdFuncion());
        comboHorarios2.removeAllItems();
        for(String e : horarios) {
            comboHorarios2.addItem(e);
        }
    }

    private void datosPelicula3() {
        funcion = obtenerFuncion("5");
        
        pelicula = obtenerPelicula("" + funcion.getIdPelicula());
        lblNombrePelicula3.setText("" + pelicula.getNombre());
        
        obtenerHorarios("" + funcion.getIdFuncion());
        comboHorarios3.removeAllItems();
        for(String e : horarios) {
            comboHorarios3.addItem(e);
        }
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\DELL\\Downloads\\faviconCinepolis.png"));
    }
}
